name: cloud-media-uploader
region: fra

services:
  - name: web
    github:
      repo: karimlifatimaa/cloud-media-uploader
      branch: main
      deploy_on_push: true
    
    build_command: ./gradlew clean build -x test
    run_command: java -jar build/libs/cloud-media-uploader-0.0.1-SNAPSHOT.jar
    
    environment_slug: java
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    http_port: 8080
    
    health_check:
      http_path: /health
    
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: DATABASE_USERNAME
        scope: RUN_TIME
        type: SECRET
      - key: DATABASE_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: DO_SPACES_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DO_SPACES_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DO_SPACES_REGION
        scope: RUN_TIME
      - key: DO_SPACES_BUCKET
        scope: RUN_TIME
      - key: DO_SPACES_ENDPOINT
        scope: RUN_TIME
